// ============================================================================
//  Contenido de los pop-ups de información rica.
//  Cada entrada se muestra en un modal con cabecera de color por categoría,
//  secciones, fórmula, ejemplo y datos reales. Objetivo: que cada elemento de
//  la interfaz se pueda entender a fondo sin salir de la app.
// ============================================================================

const COLOR = {
  Algoritmo: "#2563eb",
  Concepto: "#7c3aed",
  Métrica: "#0c9f6e",
  Dato: "#0891b2",
  Control: "#d97706",
  Interfaz: "#0891b2",
};

export const INFO = {
  // ───────────────────────── ALGORITMOS ─────────────────────────
  dqn: {
    emoji: "🎯", titulo: "DQN — Deep Q-Network", categoria: "Algoritmo",
    resumen: "Aprende cuánto vale cada acción y elige la mejor.",
    secciones: [
      { h: "¿Qué es?", cuerpo: "DQN aprende una función <b>Q(s,a)</b>: dado el estado, estima la recompensa futura total de cada acción. Actuar es entonces trivial: elige la de mayor Q. Lo «deep» es que esa función es una <b>red neuronal</b>, capaz de generalizar a estados nunca vistos." },
      { h: "¿Cómo funciona?", cuerpo: "Guarda experiencias en un <b>replay buffer</b> y entrena con minibatches aleatorios. Explora con <b>ε-greedy</b>. Para no «perseguir su propia sombra» usa una <b>red objetivo</b> (copia lenta) y, aquí, <b>Double DQN</b> (separa quién elige y quién evalúa la acción) + pérdida <b>Huber</b>." },
      { h: "Lo que ves en pantalla", cuerpo: "El inspector muestra los 3 valores Q (la acción greedy, en verde). Las curvas: recompensa al alza, ε decayendo y el buffer llenándose." },
    ],
    formula: "objetivo = r + γ · (1−done) · maxₐ' Q⁻(s', a')",
    dato: "Red 6→128→128→3 · replay 100.000 · ε 1.0→0.05 · γ=0.99 · off-policy, basado en valor.",
  },
  ppo: {
    emoji: "🧗", titulo: "PPO — Proximal Policy Optimization", categoria: "Algoritmo",
    resumen: "Mejora la política a pasos pequeños y controlados.",
    secciones: [
      { h: "¿Qué es?", cuerpo: "En vez de estimar el valor de cada acción, PPO ajusta <b>directamente la política</b> π(a|s) (probabilidad de cada acción). Una segunda red, la <b>crítica</b>, estima V(s) y sirve para juzgar si una acción fue mejor o peor de lo esperado (la <b>ventaja</b>)." },
      { h: "¿Cómo funciona?", cuerpo: "Es <b>on-policy</b>: recoge un <b>rollout</b> (256 pasos × N entornos), calcula las ventajas con <b>GAE</b>, y optimiza unas épocas con un objetivo <b>recortado</b> que impide cambiar la política demasiado de golpe. Luego descarta los datos." },
      { h: "Lo que ves en pantalla", cuerpo: "El inspector muestra π(a|s) como barras de probabilidad, el valor V(s) y la entropía. La gráfica de exploración sigue a la entropía (no a ε)." },
    ],
    formula: "L = E[ min( ρ·A , clip(ρ, 1−ε, 1+ε)·A ) ]   ·   ρ = π_nueva / π_vieja",
    dato: "Actor 6→128→128→3 · Crítica →1 · rollout 256 · 4 épocas · clip ε=0.2 · GAE λ=0.95.",
  },
  sac: {
    emoji: "🎲", titulo: "SAC — Soft Actor-Critic (discreto)", categoria: "Algoritmo",
    resumen: "Maximiza recompensa Y aleatoriedad, y se autorregula.",
    secciones: [
      { h: "¿Qué es?", cuerpo: "Actor-crítico <b>off-policy</b> de <b>máxima entropía</b>: no solo busca recompensa, también mantener la política algo aleatoria (entropía) para no cerrarse pronto en una sola estrategia." },
      { h: "¿Cómo funciona?", cuerpo: "Usa <b>dos críticos</b> Q y toma el <b>mínimo</b> (evita sobreestimar). Una <b>temperatura α</b> pondera la entropía y <b>se ajusta sola</b> hacia una entropía objetivo: si explora poco, α sube; si explora demasiado, baja." },
      { h: "Lo que ves en pantalla", cuerpo: "El inspector muestra la política, la temperatura α y la entropía. La curva de exploración sigue a α (en nuestras corridas baja de 0.20 a ~0.16 sola)." },
    ],
    formula: "y = r + γ · Σₐ π(a|s')·[ min(Q1', Q2') − α·log π(a|s') ]",
    dato: "Actor + 2 críticos + 2 objetivo · α aprendible · entropía objetivo 0.55·log 3 · off-policy.",
  },
  worldModel: {
    emoji: "🧠", titulo: "World Model — Dyna-Q", categoria: "Algoritmo",
    resumen: "Aprende un modelo del juego y entrena «imaginando».",
    secciones: [
      { h: "¿Qué es?", cuerpo: "Los otros tres son <b>model-free</b> (no entienden el entorno). Este es <b>model-based</b>: aprende un <b>modelo de la dinámica</b> que predice, dado (s,a), el siguiente estado, la recompensa y si termina." },
      { h: "¿Cómo funciona?", cuerpo: "Con datos reales entrena el modelo y un Q-net (como DQN). Además, el modelo genera transiciones <b>imaginadas</b> con las que entrena el Q-net otras veces más (Dyna-Q): por cada paso real, 5 actualizaciones imaginadas. Predice el incremento Δs (más estable)." },
      { h: "Lo que ves en pantalla", cuerpo: "Las métricas se adaptan: aparecen «Error del modelo» y «Planning». El inspector compara el estado real con el predicho componente a componente." },
    ],
    formula: "s' = s + Δs_pred   ·   error del modelo = RMSE(s'_pred, s'_real)",
    dato: "Q-net 6→128→128→3 · Modelo (6+3)→200→200→(Δs,r,done) · planning 5 · off-policy.",
  },

  // ───────────────────────── CONCEPTOS ─────────────────────────
  modelFree: { emoji:"🚀", titulo:"Model-free", categoria:"Concepto",
    resumen:"Aprende qué hacer sin modelar el entorno.",
    secciones:[{h:"Idea",cuerpo:"Aprende directamente una política o una función de valor a partir de la experiencia, <b>sin</b> predecir el siguiente estado. No sabe «física»; solo asocia situaciones con buenas acciones."},
      {h:"Ejemplo",cuerpo:"DQN aprende Q(s,a) probando acciones y observando recompensas, sin saber jamás cómo se mueve la pelota."}] },
  modelBased: { emoji:"🔮", titulo:"Model-based", categoria:"Concepto",
    resumen:"Aprende un modelo del entorno y lo usa para planificar.",
    secciones:[{h:"Idea",cuerpo:"Aprende un modelo de la dinámica (dado (s,a) ¿cuál es s' y r?) y lo usa para planificar o generar experiencia imaginada. Más eficiente en datos, pero sufre si el modelo se equivoca (<b>model bias</b>)."},
      {h:"Ejemplo",cuerpo:"El World Model predice dónde estará la pelota tras una acción y entrena al agente con esas predicciones."}] },
  replay: { emoji:"🗃️", titulo:"Replay buffer", categoria:"Concepto",
    resumen:"Memoria de experiencias pasadas para entrenar.",
    secciones:[{h:"Idea",cuerpo:"Almacena transiciones (s,a,r,s',done) y muestrea lotes aleatorios. Rompe la <b>correlación temporal</b> entre pasos consecutivos (que desestabiliza) y <b>reutiliza</b> cada experiencia muchas veces."},
      {h:"¿Quién lo usa?",cuerpo:"Los métodos <b>off-policy</b>: DQN, SAC y World Model. PPO no (es on-policy)."}],
    dato:"Aquí: 100.000 transiciones, minibatches de 128." },
  targetNet: { emoji:"🎯", titulo:"Red objetivo", categoria:"Concepto",
    resumen:"Copia estable para calcular los objetivos.",
    secciones:[{h:"Idea",cuerpo:"Una copia de la red que se actualiza lentamente y sirve para fijar el objetivo TD. Sin ella, el objetivo se movería a cada paso junto con la red que entrenamos («perseguir tu propia sombra») y divergería."}],
    formula:"θ⁻ ← τ·θ + (1−τ)·θ⁻   (Polyak, τ=0.01)" },
  epsilon: { emoji:"🎲", titulo:"Exploración ε-greedy", categoria:"Concepto",
    resumen:"Acción al azar con probabilidad ε.",
    secciones:[{h:"Idea",cuerpo:"Con probabilidad <b>ε</b> el agente actúa al azar (explorar); el resto del tiempo elige la mejor acción conocida (explotar). Sin exploración nunca descubriría algo mejor que lo que ya conoce."},
      {h:"Detalle",cuerpo:"ε empieza alto (explorar) y <b>decae</b> con el tiempo (explotar lo aprendido)."}],
    dato:"Aquí: ε pasa de 1.0 a 0.05 en 25.000 pasos." },
  politicaEstocastica: { emoji:"🎰", titulo:"Política estocástica", categoria:"Concepto",
    resumen:"Distribución de probabilidad sobre acciones.",
    secciones:[{h:"Idea",cuerpo:"En vez de elegir siempre la mejor acción, la política devuelve π(a|s) y se muestrea de ella. Aporta exploración natural y permite optimizar la política con gradientes."},
      {h:"Ejemplo",cuerpo:"PPO y SAC dan [0.2, 0.5, 0.3] para [←, ·, →] y muestrean."}] },
  ventajaGae: { emoji:"📐", titulo:"Ventaja (GAE)", categoria:"Concepto",
    resumen:"¿Cuánto mejor fue una acción que la media?",
    secciones:[{h:"Idea",cuerpo:"La ventaja A(s,a)=Q(s,a)−V(s) mide cuánto mejor es una acción respecto al valor medio del estado. <b>GAE</b> la estima combinando errores TD de varios pasos con un factor λ que equilibra sesgo y varianza."}],
    formula:"A_t = Σ (γλ)ˡ · δ_{t+l}   ·   δ = r + γV(s') − V(s)" },
  clipSurrogate: { emoji:"✂️", titulo:"Objetivo recortado (clip)", categoria:"Concepto",
    resumen:"Limita cuánto cambia la política por paso.",
    secciones:[{h:"Idea",cuerpo:"PPO mide el ratio entre la política nueva y la vieja y lo <b>recorta</b> a [1−ε, 1+ε]. Así nunca da un paso tan grande que arruine la política, sin necesidad de restricciones complejas."}],
    formula:"con ε=0.2 → el ratio se limita a [0.8, 1.2]" },
  onPolicy: { emoji:"📜", titulo:"On-policy / rollouts", categoria:"Concepto",
    resumen:"Entrena solo con datos de la política actual.",
    secciones:[{h:"Idea",cuerpo:"Un método <b>on-policy</b> solo aprende de experiencias de su política actual; tras actualizar, los datos viejos ya no sirven. Recoge «rollouts», los procesa unas épocas y los descarta. Más estable pero menos eficiente en datos que off-policy."}] },
  dobleCritico: { emoji:"⚖️", titulo:"Doble crítico (clipped double-Q)", categoria:"Concepto",
    resumen:"Dos redes Q; se usa la menor.",
    secciones:[{h:"Idea",cuerpo:"Mantener dos críticos y usar el <b>mínimo</b> al calcular el objetivo reduce la <b>sobreestimación</b> sistemática de Q (un problema clásico que lleva a políticas malas). Lo usan SAC y TD3."}],
    formula:"target = r + γ · min(Q1', Q2')" },
  maxEntropia: { emoji:"🌪️", titulo:"Máxima entropía", categoria:"Concepto",
    resumen:"Recompensa también ser impredecible.",
    secciones:[{h:"Idea",cuerpo:"SAC maximiza recompensa <b>y</b> entropía de la política. Esto mantiene la exploración, evita colapsar pronto en una sola acción y mejora la robustez."}],
    formula:"objetivo = E[ r + α·H(π) ]" },
  temperaturaAuto: { emoji:"🌡️", titulo:"Temperatura α automática", categoria:"Concepto",
    resumen:"Ajusta el peso de la entropía sola.",
    secciones:[{h:"Idea",cuerpo:"El coeficiente α que pondera la entropía se ajusta por gradiente para alcanzar una <b>entropía objetivo</b>. Así no hay que afinarlo a mano para cada tarea."}],
    dato:"Aquí la entropía objetivo es 0.55·log(3)." },
  modeloDinamica: { emoji:"🔭", titulo:"Modelo de dinámica", categoria:"Concepto",
    resumen:"Red que predice (s,a) → (s', r, done).",
    secciones:[{h:"Idea",cuerpo:"Una red entrenada de forma <b>supervisada</b> para predecir el siguiente estado, la recompensa y si termina. Es el corazón de los métodos model-based. Predecimos el incremento Δs (más estable que s' directo)."}],
    dato:"Error RMSE del modelo ~0.07–0.15 sobre estados normalizados." },
  planning: { emoji:"💭", titulo:"Planning / imaginación", categoria:"Concepto",
    resumen:"Entrena con experiencia simulada por el modelo.",
    secciones:[{h:"Idea",cuerpo:"Con un modelo de dinámica se generan transiciones <b>imaginadas</b> (sin tocar el entorno real) y se entrena la política/valor también con ellas (<b>Dyna-Q</b>). Multiplica los datos de entrenamiento por cada paso real."}],
    dato:"Aquí: 5 actualizaciones imaginadas por paso real." },

  // ───────────────────────── MÉTRICAS / DATOS ─────────────────────────
  rewardMedio100: { emoji:"🏆", titulo:"Recompensa media (·100)", categoria:"Métrica",
    resumen:"La métrica principal: si sube, el agente aprende.",
    secciones:[{h:"Qué mide",cuerpo:"La recompensa media de los <b>últimos 100 episodios</b>. Es el resumen de lo bien que juega el agente ahora mismo."},
      {h:"Cómo leerla",cuerpo:"Debe <b>subir</b> con el entrenamiento. Puede oscilar (RL es ruidoso), pero la tendencia importa. Negativa al principio (pierde la bola), positiva cuando aprende a devolverla y romper ladrillos."}] },
  loss: { emoji:"📉", titulo:"Pérdida", categoria:"Métrica",
    resumen:"El error de la red en cada actualización.",
    secciones:[{h:"Qué mide",cuerpo:"Cuánto se equivoca la red respecto a su objetivo en cada paso de gradiente."},
      {h:"Cómo leerla",cuerpo:"<b>Ojo:</b> en RL no tiene que bajar siempre (el objetivo se mueve con la propia red). Lo importante es que <b>no diverja</b> (no se dispare a infinito)."}] },
  tdError: { emoji:"⚡", titulo:"TD-error", categoria:"Métrica",
    resumen:"La «sorpresa» de la red ante una transición.",
    secciones:[{h:"Qué mide",cuerpo:"La diferencia entre lo que la red predecía y el objetivo de Bellman. Un TD-error grande = experiencia muy informativa (con replay prioritario se repetiría más)."}],
    formula:"TD = (r + γ·maxQ⁻(s',·)) − Q(s,a)" },
  bufferSize: { emoji:"🗃️", titulo:"Tamaño del buffer", categoria:"Métrica",
    resumen:"Cuántas experiencias hay en memoria.",
    secciones:[{h:"Qué mide",cuerpo:"Cuántas transiciones lleva guardadas el replay buffer (hasta su capacidad). Al principio el agente entrena poco hasta que el buffer tiene datos suficientes."}],
    dato:"Capacidad: 100.000. Arranca a entrenar tras ~1.500–2.000 experiencias." },
  tasaExito100: { emoji:"🥇", titulo:"Tasa de éxito", categoria:"Métrica",
    resumen:"% de partidas en que limpia todos los ladrillos.",
    secciones:[{h:"Qué mide",cuerpo:"Porcentaje de los últimos 100 episodios en que el agente <b>completó el nivel</b> (rompió los 28 ladrillos). Es difícil: requiere mucho entrenamiento."}] },
  entropia: { emoji:"🌪️", titulo:"Entropía de la política", categoria:"Métrica",
    resumen:"Cuán aleatoria es la política.",
    secciones:[{h:"Qué mide",cuerpo:"Alta = explora mucho (probabilidades repartidas); baja = la política se ha «afilado» hacia pocas acciones."},
      {h:"Cómo leerla",cuerpo:"Suele <b>bajar despacio</b> al aprender. Si cae a cero muy pronto, el agente dejó de explorar demasiado rápido."}],
    dato:"Máximo posible con 3 acciones: log(3) ≈ 1.10." },
  temperatura: { emoji:"🌡️", titulo:"Temperatura α (SAC)", categoria:"Métrica",
    resumen:"El peso de la entropía, ajustado solo.",
    secciones:[{h:"Qué mide",cuerpo:"Cuánto premia SAC mantener la exploración. <b>Se ajusta automáticamente</b>: si la política explora poco, α sube; si demasiado, baja."}],
    dato:"En nuestras corridas baja de 0.20 a ~0.16." },
  errorModelo: { emoji:"🔭", titulo:"Error del modelo (World Model)", categoria:"Métrica",
    resumen:"Cómo de bien predice el modelo el futuro.",
    secciones:[{h:"Qué mide",cuerpo:"El error RMSE entre el estado siguiente <b>predicho</b> por el modelo y el real. Cuanto más bajo, más fiables son las experiencias imaginadas."},
      {h:"Cómo leerla",cuerpo:"Debe <b>bajar</b>. Si es alto, el agente está aprendiendo de un mundo falso (model bias)."}],
    dato:"Buen valor aquí: RMSE ~0.07 sobre estados normalizados a [-1,1]." },
  pasosPlanning: { emoji:"💭", titulo:"Pasos de planning", categoria:"Métrica",
    resumen:"Actualizaciones imaginadas por paso real.",
    secciones:[{h:"Qué mide",cuerpo:"Cuántas veces se entrena el Q-net con experiencia <b>imaginada</b> por el modelo en cada paso real. Multiplica el aprendizaje si el modelo es bueno."}],
    dato:"Aquí: 5." },
  lossValor: { emoji:"📉", titulo:"Pérdida de la crítica (PPO)", categoria:"Métrica",
    resumen:"Cómo de bien estima la crítica el valor V(s).",
    secciones:[{h:"Qué mide",cuerpo:"El error de la red <b>crítica</b> al predecir el retorno (el valor del estado). Una crítica precisa da mejores estimaciones de la <b>ventaja</b>, y por tanto mejores actualizaciones del actor."},
      {h:"Cómo leerla",cuerpo:"Suele bajar conforme la crítica aprende, aunque puede repuntar tras recoger un rollout nuevo."}] },
  rolloutProgreso: { emoji:"📜", titulo:"Rollout (PPO)", categoria:"Métrica",
    resumen:"Cuánto lleva lleno el rollout on-policy.",
    secciones:[{h:"Qué mide",cuerpo:"PPO recoge 256 pasos por entorno antes de cada actualización. Esta barra indica cuánto falta para la siguiente: al llegar al 100% entrena y vacía el rollout."}] },

  // ───────────────────────── LA INTERFAZ (paneles y vistas) ─────────────────────────
  lab: { emoji:"🧠", titulo:"Arkanoid DRL Learning Lab", categoria:"Interfaz",
    resumen:"Un laboratorio para ver y entender cómo aprende un agente.",
    secciones:[{h:"Qué es",cuerpo:"Un entorno donde 4 algoritmos de aprendizaje por refuerzo aprenden a jugar al Arkanoid <b>de verdad</b> (redes neuronales reales sobre la GPU). No se les explican las reglas: las descubren jugando."},
      {h:"El bucle",cuerpo:"El agente observa el <b>estado</b>, elige una <b>acción</b>, el entorno responde con <b>recompensa</b> y nuevo estado, y el agente ajusta su <b>política</b>. Repetido miles de veces, eso es aprender."},
      {h:"Cómo usarlo",cuerpo:"Elige un algoritmo arriba, pulsa <b>▶ Entrenar</b> y observa la partida, las métricas, el inspector y las curvas. Pasa el ratón o pulsa cualquier ℹ para entender cada pieza."}],
    formula:"estado → acción → recompensa → estado' → (repite)" },
  partidaObservada: { emoji:"🎮", titulo:"Partida observada", categoria:"Interfaz",
    resumen:"Una ventana para ver jugar al agente.",
    secciones:[{h:"Qué ves",cuerpo:"Una de las partidas que juega el agente con su política <b>actual</b>. La <b>pala</b> es la única acción controlable (← · →); la <b>pelota</b> y los ladrillos son la dinámica del entorno."},
      {h:"Importante",cuerpo:"Es solo observación: estas partidas no entrenan al agente (eso lo hacen cientos de entornos sin dibujar). Aquí ves cómo se comporta la política mientras mejora."}] },
  inspector: { emoji:"🔬", titulo:"Inspector del algoritmo", categoria:"Interfaz",
    resumen:"La «radiografía» de lo que piensa el agente ahora.",
    secciones:[{h:"Qué muestra",cuerpo:"Cambia según el algoritmo: en DQN/World Model, los <b>valores Q</b> de cada acción; en PPO/SAC, las <b>probabilidades</b> de la política y el valor del estado. Es lo que el agente «cree» del estado observado."},
      {h:"Para qué",cuerpo:"Permite ver por qué el agente elige una acción y cómo evolucionan sus estimaciones con el entrenamiento."}] },
  curvas: { emoji:"📈", titulo:"Curvas de entrenamiento", categoria:"Interfaz",
    resumen:"Cómo evoluciona el aprendizaje en el tiempo.",
    secciones:[{h:"Cómo leerlas",cuerpo:"<b>Recompensa</b> (verde): la principal, debe subir. <b>Pérdida</b>: no tiene que bajar siempre, pero no debe diverger. Las otras dos se adaptan al algoritmo (buffer/ε, entropía/α, error del modelo…)."},
      {h:"Detalle",cuerpo:"Cada punto se registra cada 250 pasos. Es normal que oscilen: el RL es ruidoso; mira la tendencia."}] },
  selectorAlgoritmo: { emoji:"🧩", titulo:"Versión del experimento", categoria:"Interfaz",
    resumen:"Elige qué cerebro pilota al agente.",
    secciones:[{h:"Qué hace",cuerpo:"Los 4 algoritmos resuelven el mismo juego con filosofías distintas. Al cambiar de uno a otro se <b>recrea el agente desde cero</b> y toda la interfaz (métricas, curvas, inspector, conceptos) se adapta."},
      {h:"Consejo",cuerpo:"Pulsa la ℹ de cada tarjeta para una explicación a fondo del algoritmo."}] },
  controlEjecucion: { emoji:"⚙️", titulo:"Control de ejecución", categoria:"Interfaz",
    resumen:"Cómo corre la simulación (no afecta a lo que aprende).",
    secciones:[{h:"Qué controla",cuerpo:"La velocidad, cuántos entornos generan datos y cuántos se dibujan, y el reward shaping. Salvo el shaping, nada de esto cambia la física ni el modelo: solo el ritmo y la cantidad de datos."}] },
  entornosParalelos: { emoji:"🪟", titulo:"Entornos en paralelo", categoria:"Interfaz",
    resumen:"Muchas partidas con la misma política.",
    secciones:[{h:"Por qué varias",cuerpo:"Todas usan el <b>mismo</b> cerebro. Verlas a la vez ayuda a juzgar si la política es buena en general y no por suerte en una partida concreta."},
      {h:"Dos pools",cuerpo:"Estas son del pool <b>visual</b> (pocas, se dibujan). El entrenamiento de verdad usa cientos de entornos <b>headless</b> sin dibujar. Pincha una para inspeccionarla arriba."}] },
  panelConceptos: { emoji:"📚", titulo:"Conceptos de DRL", categoria:"Interfaz",
    resumen:"Qué técnicas usa (y cuáles no) este algoritmo.",
    secciones:[{h:"Para qué",cuerpo:"El RL profundo es un menú de técnicas; cada método combina unas pocas. Esta tabla marca cuáles están activas en el algoritmo seleccionado, para ver las diferencias de un vistazo. Pulsa la ℹ de cada concepto para entenderlo."}] },
  flujoDatos: { emoji:"🔄", titulo:"Flujo de datos", categoria:"Interfaz",
    resumen:"El recorrido de una experiencia, de principio a fin.",
    secciones:[{h:"Qué muestra",cuerpo:"Desde que los entornos generan datos hasta que la política mejorada vuelve a actuar. Se adapta: off-policy usa replay buffer; on-policy usa rollouts; el World Model añade un modelo de dinámica."}] },
  replayPanel: { emoji:"🗃️", titulo:"Replay buffer (conceptual)", categoria:"Interfaz",
    resumen:"Las experiencias arquetípicas y su recompensa.",
    secciones:[{h:"Qué ves",cuerpo:"Las transiciones (s,a,r,s',done) más típicas con su recompensa real y su <b>TD-error</b>. Las más informativas (perder la bola, romper un ladrillo) tienen mayor TD-error y, con replay prioritario, se repetirían más al entrenar."}] },
  familias: { emoji:"🎓", titulo:"Las cuatro familias", categoria:"Interfaz",
    resumen:"El mapa del RL profundo en este laboratorio.",
    secciones:[{h:"Qué muestra",cuerpo:"Resumen de los 4 algoritmos: su familia (basado en valor / actor-crítico / model-based), si son on/off-policy y qué aprenden. El recuadro resaltado es el activo."}] },
  transicion: { emoji:"🔗", titulo:"Transición actual", categoria:"Interfaz",
    resumen:"La unidad mínima de aprendizaje, en vivo.",
    secciones:[{h:"Qué es",cuerpo:"Cada paso del entorno produce una tupla <b>(s, a, r, s', done)</b>: dónde estaba, qué hizo, qué ganó, a dónde fue y si terminó. Estas tuplas son los «datos» con los que entrena la red."}] },

  // ───────────────────────── CONTROLES ─────────────────────────
  velocidad: { emoji:"⏩", titulo:"Velocidad de simulación", categoria:"Control",
    resumen:"Avance rápido: no cambia el modelo, solo el ritmo.",
    secciones:[{h:"Qué hace",cuerpo:"Cuántos pasos de simulación ocurren por frame, tanto en el <b>entrenamiento</b> como en la <b>animación</b>. Es un fast-forward."},
      {h:"Clave",cuerpo:"<b>NO cambia la física ni el modelo</b>: la pelota se mueve igual por paso; solo pasan más pasos por segundo. Súbela para ver/aprender más rápido; bájala para observar con calma."}] },
  poolHeadless: { emoji:"🏭", titulo:"Entornos de entrenamiento (headless)", categoria:"Control",
    resumen:"Las partidas que de verdad generan los datos.",
    secciones:[{h:"Qué hace",cuerpo:"Entornos <b>sin dibujar</b> que producen las experiencias para entrenar. Más entornos = más datos por segundo y gradientes más estables. Se ejecutan en batch en la GPU."}],
    dato:"De 50 a 2.000. Por defecto 256." },
  poolVisual: { emoji:"👁️", titulo:"Entornos visuales", categoria:"Control",
    resumen:"Los pocos que se dibujan para que los veas.",
    secciones:[{h:"Qué hace",cuerpo:"Ejecutan la <b>misma política</b> del agente pero solo para observar. No generan la mayoría de los datos de entrenamiento; son una ventana."}] },
  shaping: { emoji:"🎯", titulo:"Reward shaping potencial", categoria:"Control",
    resumen:"Recompensa densa que acelera el aprendizaje.",
    secciones:[{h:"Qué hace",cuerpo:"Añade una pequeña recompensa por acercar la pala a la pelota: Φ(s) = −|pelota.x − pala.x|. Da señal en <b>cada paso</b> (no solo al romper o perder)."},
      {h:"Por qué es seguro",cuerpo:"Es <b>telescópica</b> (potential-based, Ng et al. 1999): no cambia la política óptima, solo ayuda a aprender más rápido. Desactívalo para ver cuánto cuesta aprender sin esa pista (reinicia el agente)."}] },

  // ───────────────────────── TRANSICIÓN (componentes) ─────────────────────────
  estado: { emoji:"👁️", titulo:"Estado (s)", categoria:"Concepto",
    resumen:"Lo único que el agente percibe.",
    secciones:[{h:"Qué es",cuerpo:"Un vector de <b>6 números</b> normalizados: posición (x,y) y velocidad (vx,vy) de la pelota, posición de la pala y la distancia pelota−pala. Es la «foto» sobre la que decide."},
      {h:"En la tira",cuerpo:"Aquí mostramos un resumen legible (la x de la pelota), pero la red recibe los 6 números."}] },
  accion: { emoji:"🎮", titulo:"Acción (a)", categoria:"Concepto",
    resumen:"Lo que el agente decide hacer.",
    secciones:[{h:"Qué es",cuerpo:"Una de <b>3 acciones discretas</b>: ← izquierda, · mantener, → derecha. La política convierte el estado en esta elección."}] },
  recompensa: { emoji:"🎁", titulo:"Recompensa (r)", categoria:"Concepto",
    resumen:"El premio o castigo de este paso.",
    secciones:[{h:"Qué es",cuerpo:"El número que guía al agente. Suma de los eventos del paso: +1 ladrillo (+combo), +0.2 rebote, −1 perder, +5 nivel, más el shaping. El agente solo busca maximizar su suma a largo plazo."}] },
  estadoSiguiente: { emoji:"➡️", titulo:"Estado siguiente (s')", categoria:"Concepto",
    resumen:"A dónde llevó la acción.",
    secciones:[{h:"Qué es",cuerpo:"El estado al que se llega tras aplicar la acción. La red lo usa para estimar el valor del <b>futuro</b> (la parte γ·Q(s') de la ecuación de Bellman)."}] },
  done: { emoji:"🏁", titulo:"¿Terminado? (done)", categoria:"Concepto",
    resumen:"Si el episodio acabó en este paso.",
    secciones:[{h:"Qué es",cuerpo:"<b>true</b> si se perdió la bola, se limpió el nivel o se agotó el tiempo. Cuando es true, al calcular el objetivo NO se mira el futuro (no hay s' que valga: el episodio terminó)."}] },

  // ───────────────────────── DATO DE PARTIDA ─────────────────────────
  rewardEpisodio: { emoji:"🏆", titulo:"Recompensa del episodio", categoria:"Métrica",
    resumen:"Lo acumulado en la partida que observas.",
    secciones:[{h:"Qué mide",cuerpo:"La suma de premios y castigos del episodio actual de la partida observada. Es la cifra que el agente intenta maximizar; al terminar el episodio se reinicia."}] },
};

const COLOR_SOFT = {
  Algoritmo: "#eff4fe",
  Concepto: "#f4effe",
  Métrica: "#e9fbf4",
  Dato: "#e7f7fb",
  Control: "#fef3e6",
  Interfaz: "#e7f7fb",
};

export function colorCategoria(cat) {
  return COLOR[cat] || "#2563eb";
}
export function colorSoftCategoria(cat) {
  return COLOR_SOFT[cat] || "#eff4fe";
}
